FROM nvidia/cuda:10.0-devel

# see instructions in PDF on how to run Dockerfile
Run apt-get update

Run apt-get -y install python3

Run apt-get -y install python3-pip

Run pip3 install jupyterlab

Run pip3 install jupyter

WORKDIR /home/